Repository replugged-org/guide, pull requests merged in 2023-06, with the labels that each got.

#24 feat: document button popover props
  cspell.json
  docs/plugins/injecting.mdx
  docs/plugins/modules/common.mdx
  docs/plugins/modules/components.mdx
  docs/plugins/settings.md
  src/components/APIReferences.tsx
Labels: enhancement, page improvements

#25 feat: document context menus
  docs/plugins/modules/common.mdx
  docs/plugins/modules/components.mdx
Labels: enhancement, page improvements

#26 fix: icon prop type
  docs/plugins/injecting.mdx
  docs/plugins/modules/components.mdx
Labels: bug, page improvements

#27 Manifest keys
  docs/contributing/_category_.yml
  docs/manifest.mdx
  docs/plugins/getting-started.md
  docs/store.md
  docs/themes/getting-started.md
Labels: new page

#30 feat: v4.5.0 update
  docs/plugins/modules/common.mdx
  docs/plugins/modules/index.md
Labels: enhancement, page improvements
